name: Build Monkas
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: gradle
      - name: Build
        run: ./gradlew build
      - name: Publish artifacts
        - uses: actions/upload-artifact@v3
        with:
          name: monkas-addon
          path: ./build/libs/*.jar
